import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import * as policeController from '../controllers/policeController';

const router = Router();

router.post('/initialize', authenticate, policeController.initialize);
router.get('/dashboard', authenticate, policeController.dashboard);
router.get('/officers', authenticate, policeController.officers);
router.get('/units', authenticate, policeController.units);
router.patch('/status', authenticate, policeController.updateStatus);
router.get('/dispatches', authenticate, policeController.dispatches);
router.post('/dispatches', authenticate, policeController.createDispatch);
router.patch('/dispatches/:id', authenticate, policeController.updateDispatch);
router.get('/bolos', authenticate, policeController.bolos);
router.post('/bolos', authenticate, policeController.createBolo);
router.get('/warrants', authenticate, policeController.warrants);
router.post('/warrants', authenticate, policeController.createWarrant);
router.get('/wanted', authenticate, policeController.wanted);
router.get('/reports', authenticate, policeController.reports);
router.post('/reports', authenticate, policeController.createReport);
router.post('/citations', authenticate, policeController.createCitation);
router.get('/cases', authenticate, policeController.cases);
router.post('/cases', authenticate, policeController.createCase);
router.get('/evidence', authenticate, policeController.evidence);
router.post('/evidence', authenticate, policeController.createEvidence);
router.post('/search', authenticate, policeController.search);
router.post('/panic', authenticate, policeController.panic);
router.get('/analytics', authenticate, policeController.analytics);
router.get('/gangs', authenticate, policeController.gangs);
router.get('/organizations', authenticate, policeController.organizations);
router.post('/notes', authenticate, policeController.createNote);
router.post('/track', authenticate, policeController.track);
router.get('/citizens/:userId/bank', authenticate, policeController.citizenBank);
router.get('/citizens/:userId/gps', authenticate, policeController.liveGps);
router.get('/rbac', authenticate, policeController.rbac);
router.patch('/rbac', authenticate, policeController.updateRbac);
router.get('/fine-calculator', authenticate, policeController.fineCalculator);

export default router;
