import { App } from '../database/models/App';
import { Developer } from '../database/models/Developer';
import { StoreListing } from '../database/models/StoreListing';
import { AppVersion } from '../database/models/AppVersion';
import { StoreReview } from '../database/models/StoreReview';

const STORE_APPS = [
  {
    bundleId: 'com.gulfos.identity',
    name: 'Identity',
    version: '1.0.0',
    description: 'Digital identity card with verification',
    icon: '🪪',
    category: 'utilities' as const,
    permissions: ['storage', 'camera'] as const,
    tagline: 'Your digital identity, verified.',
    longDescription: 'Premium digital identity for GULFOS with QR verification, PDF export, and admin verification.',
    screenshots: ['🪪', '📱', '✅'],
    featured: true,
    trending: true,
    editorsChoice: true,
    recommended: true,
    verified: true,
    premium: false,
    storageSize: 180_000_000,
    trendingScore: 98,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.bank',
    name: 'GULF Bank',
    version: '2.1.0',
    description: 'Advanced digital banking',
    icon: '🏦',
    category: 'finance' as const,
    permissions: ['network', 'notifications', 'biometrics'] as const,
    tagline: 'Banking reimagined.',
    longDescription: 'Full-featured banking with transfers, QR payments, analytics, and fraud detection.',
    screenshots: ['🏦', '💳', '📊'],
    featured: true,
    trending: true,
    editorsChoice: true,
    recommended: true,
    verified: true,
    premium: true,
    price: 0,
    storageSize: 480_000_000,
    trendingScore: 95,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.phone',
    name: 'Phone',
    version: '1.2.0',
    description: 'Calls, voicemail, and favorites',
    icon: '📞',
    category: 'communication' as const,
    permissions: ['microphone', 'contacts', 'notifications'] as const,
    tagline: 'Crystal clear calls.',
    longDescription: 'Full telephony with dial pad, conference calls, and beautiful call animations.',
    screenshots: ['📞', '⭐', '📋'],
    featured: true,
    trending: true,
    recommended: true,
    verified: true,
    storageSize: 320_000_000,
    trendingScore: 92,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.messages',
    name: 'Messages',
    version: '1.1.0',
    description: 'SMS with attachments and read receipts',
    icon: '💬',
    category: 'communication' as const,
    permissions: ['contacts', 'photos', 'camera', 'microphone', 'notifications'] as const,
    tagline: 'Message beautifully.',
    longDescription: 'Rich messaging with voice notes, media sharing, and realtime delivery.',
    screenshots: ['💬', '📷', '🎤'],
    featured: false,
    trending: true,
    recommended: true,
    verified: true,
    storageSize: 260_000_000,
    trendingScore: 88,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.police',
    name: 'GULF Police',
    version: '1.0.0',
    description: 'Professional police platform',
    icon: '🚔',
    category: 'utilities' as const,
    permissions: ['location', 'camera', 'notifications', 'network'] as const,
    tagline: 'Serve and protect.',
    longDescription: 'Dispatch, reports, tickets, and internal communication for law enforcement.',
    screenshots: ['🚔', '📋', '🗺️'],
    featured: true,
    trending: false,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 1_400_000_000,
    trendingScore: 75,
    developer: { slug: 'gulfos-gov', name: 'GULFOS Government', verified: true },
  },
  {
    bundleId: 'com.gulfos.poetry',
    name: 'GULF Poetry',
    version: '1.0.0',
    description: 'Official server poetry platform',
    icon: '📜',
    category: 'social' as const,
    permissions: ['network', 'storage', 'notifications', 'microphone'] as const,
    tagline: 'Verses of the Gulf.',
    longDescription: 'Publish poems, spoken word, national verses, competitions, and official writings from the Server Poet.',
    screenshots: ['📜', '🎙️', '✨'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 520_000_000,
    trendingScore: 88,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.browser',
    name: 'GULF Browser',
    version: '1.0.0',
    description: 'Official GULFOS web browser',
    icon: '🌐',
    category: 'utilities' as const,
    permissions: ['network', 'storage', 'notifications', 'camera', 'microphone', 'location', 'biometrics'] as const,
    tagline: 'Browse the Gulf.',
    longDescription: 'Official web browser with GULF Search, secure portals, downloads, bookmarks, private browsing, and ecosystem integrations.',
    screenshots: ['🌐', '🔒', '📥'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 680_000_000,
    trendingScore: 95,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.chat',
    name: 'GULF Chat',
    version: '1.0.0',
    description: 'Official GULFOS instant messaging platform',
    icon: '💬',
    category: 'communication' as const,
    permissions: ['network', 'contacts', 'storage', 'notifications', 'microphone', 'camera', 'photos', 'biometrics'] as const,
    tagline: 'Message the Gulf.',
    longDescription: 'Private and group chats, channels, communities, voice and video calls, end-to-end encryption, and full GULFOS ecosystem integration.',
    screenshots: ['💬', '📞', '🔒'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 280_000_000,
    trendingScore: 98,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
  },
  {
    bundleId: 'com.gulfos.justice',
    name: 'GULF Justice',
    version: '1.0.0',
    description: 'Official court and judicial system',
    icon: '⚖️',
    category: 'utilities' as const,
    permissions: ['location', 'network', 'notifications', 'storage'] as const,
    tagline: 'Justice for the Gulf.',
    longDescription: 'Complete judicial MDT for prosecutors, judges, and court staff with cases, hearings, trials, warrants, evidence, and full GULFOS ecosystem integration.',
    screenshots: ['⚖️', '📋', '🏛️'],
    featured: true,
    trending: false,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 950_000_000,
    trendingScore: 70,
    developer: { slug: 'gulfos-gov', name: 'GULFOS Government', verified: true },
  },
  {
    bundleId: 'com.gulfos.ems',
    name: 'GULF EMS',
    version: '1.0.0',
    description: 'Official Emergency Medical Services platform',
    icon: '🚑',
    category: 'utilities' as const,
    permissions: ['location', 'network', 'notifications', 'camera'] as const,
    tagline: 'Saving lives across the Gulf.',
    longDescription: 'Complete EMS MDT with dispatch, ambulance tracking, patient records, hospital management, and full GULFOS ecosystem integration.',
    screenshots: ['🚑', '🏥', '📋'],
    featured: true,
    trending: false,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 1_100_000_000,
    trendingScore: 72,
    developer: { slug: 'gulfos-gov', name: 'GULFOS Government', verified: true },
  },
  {
    bundleId: 'com.gulfos.business',
    name: 'GULF Business',
    version: '1.0.0',
    description: 'Enterprise business management platform',
    icon: '🏢',
    category: 'utilities' as const,
    permissions: ['location', 'network', 'notifications', 'storage'] as const,
    tagline: 'The economic foundation of GULFOS.',
    longDescription: 'Complete business ecosystem with company registration, banking, employees, finance, inventory, analytics, customers, suppliers, and government integration.',
    screenshots: ['🏢', '📊', '💼'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 1_250_000_000,
    trendingScore: 85,
    developer: { slug: 'gulfos-gov', name: 'GULFOS Government', verified: true },
  },
  {
    bundleId: 'com.gulfos.real-estate',
    name: 'GULF Real Estate',
    version: '1.0.0',
    description: 'Official real estate management platform',
    icon: '🏠',
    category: 'utilities' as const,
    permissions: ['location', 'network', 'notifications', 'storage', 'camera'] as const,
    tagline: 'Find your place in the Gulf.',
    longDescription: 'Complete real estate ecosystem with property listings, buy/sell, rentals, leases, analytics, and full GULFOS ecosystem integration.',
    screenshots: ['🏠', '📍', '💰'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    premium: true,
    storageSize: 1_300_000_000,
    trendingScore: 88,
    developer: { slug: 'gulfos-gov', name: 'GULFOS Government', verified: true },
  },
  {
    bundleId: 'com.gulfos.social',
    name: 'GULF Social',
    version: '1.0.0',
    description: 'Social feed and trending',
    icon: '🐦',
    category: 'social' as const,
    permissions: ['photos', 'camera', 'notifications', 'network'] as const,
    tagline: 'What\'s happening?',
    longDescription: 'Original social feed with posts, replies, reposts, and verified accounts.',
    screenshots: ['🐦', '📈', '✓'],
    featured: false,
    trending: true,
    recommended: true,
    verified: true,
    storageSize: 340_000_000,
    trendingScore: 85,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: true },
  },
  {
    bundleId: 'com.gulfos.camera',
    name: 'GULF Camera',
    version: '1.0.0',
    description: 'Photo and video capture',
    icon: '📷',
    category: 'media' as const,
    permissions: ['camera', 'microphone', 'storage'] as const,
    tagline: 'Capture the moment.',
    longDescription: 'Professional camera with portrait mode, flash, zoom, and gallery integration.',
    screenshots: ['📷', '🎬', '✨'],
    featured: false,
    trending: true,
    verified: true,
    storageSize: 620_000_000,
    trendingScore: 80,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.gallery',
    name: 'GULF Gallery',
    version: '1.0.0',
    description: 'Photos, videos, albums, and memories',
    icon: '🖼️',
    category: 'media' as const,
    permissions: ['photos', 'storage'] as const,
    tagline: 'Your memories, organized.',
    longDescription: 'Browse albums, favorites, hidden photos, AI categories, and memory timeline.',
    screenshots: ['🖼️', '⭐', '📅'],
    featured: true,
    trending: true,
    verified: true,
    storageSize: 400_000_000,
    trendingScore: 85,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.maps',
    name: 'GULF Maps',
    version: '1.0.0',
    description: 'GTA map navigation with live GPS',
    icon: '🗺️',
    category: 'utilities' as const,
    permissions: ['location', 'network', 'storage'] as const,
    tagline: 'Navigate Los Santos.',
    longDescription: 'Live navigation, favorite places, offline maps, traffic, and police roadblocks.',
    screenshots: ['🗺️', '📍', '🚗'],
    featured: true,
    trending: true,
    editorsChoice: true,
    verified: true,
    storageSize: 520_000_000,
    trendingScore: 90,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.files',
    name: 'GULF Files',
    version: '1.0.0',
    description: 'Browse and manage device storage',
    icon: '📁',
    category: 'utilities' as const,
    permissions: ['storage', 'files'] as const,
    tagline: 'All your files.',
    longDescription: 'Documents, downloads, images, videos, audio, ZIP and PDF preview.',
    screenshots: ['📁', '📄', '🔍'],
    featured: false,
    trending: true,
    verified: true,
    storageSize: 180_000_000,
    trendingScore: 78,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.calendar',
    name: 'GULF Calendar',
    version: '1.0.0',
    description: 'Events, reminders, and schedules',
    icon: '📅',
    category: 'productivity' as const,
    permissions: ['notifications', 'contacts'] as const,
    tagline: 'Stay organized.',
    longDescription: 'Events, birthdays, government events, police shifts, and bank payments.',
    screenshots: ['📅', '🔔', '🏛️'],
    featured: true,
    trending: true,
    verified: true,
    storageSize: 210_000_000,
    trendingScore: 82,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.clock',
    name: 'GULF Clock',
    version: '1.0.0',
    description: 'Alarms, stopwatch, timer, world clock',
    icon: '⏰',
    category: 'utilities' as const,
    permissions: ['notifications'] as const,
    tagline: 'Time, perfected.',
    longDescription: 'Alarms with sleep schedule, stopwatch, timer, and world clocks.',
    screenshots: ['⏰', '⏱️', '🌍'],
    featured: false,
    trending: true,
    verified: true,
    storageSize: 95_000_000,
    trendingScore: 75,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.notes',
    name: 'GULF Notes',
    version: '1.0.0',
    description: 'Rich notes with checklists and voice',
    icon: '📝',
    category: 'productivity' as const,
    permissions: ['storage', 'microphone'] as const,
    tagline: 'Capture ideas.',
    longDescription: 'Rich text, images, voice notes, checklists, folders, pin and lock.',
    screenshots: ['📝', '✅', '🔒'],
    featured: false,
    trending: true,
    verified: true,
    storageSize: 150_000_000,
    trendingScore: 80,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.recorder',
    name: 'GULF Recorder',
    version: '1.0.0',
    description: 'Record, trim, and share audio',
    icon: '🎙️',
    category: 'media' as const,
    permissions: ['microphone', 'storage'] as const,
    tagline: 'Record everything.',
    longDescription: 'High-quality recording with noise reduction, bookmarks, trim, and share.',
    screenshots: ['🎙️', '✂️', '📤'],
    featured: false,
    trending: false,
    verified: true,
    storageSize: 120_000_000,
    trendingScore: 65,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.weather',
    name: 'GULF Weather',
    version: '1.0.0',
    description: 'Current, hourly, and weekly forecasts',
    icon: '🌤️',
    category: 'utilities' as const,
    permissions: ['location', 'network'] as const,
    tagline: 'Know before you go.',
    longDescription: 'Live weather from World Engine with hourly, weekly, rain, wind, and visibility.',
    screenshots: ['🌤️', '🌧️', '💨'],
    featured: true,
    trending: true,
    verified: true,
    storageSize: 130_000_000,
    trendingScore: 88,
    developer: { slug: 'gulfos-official', name: 'GULFOS Official', verified: true },
    isSystemApp: true,
  },
  {
    bundleId: 'com.gulfos.calculator',
    name: 'GULF Calculator',
    version: '1.0.0',
    description: 'Standard and scientific calculator',
    icon: '🔢',
    category: 'utilities' as const,
    permissions: [] as const,
    tagline: 'Calculate anything.',
    longDescription: 'Beautiful calculator with scientific mode and history.',
    screenshots: ['🔢'],
    featured: false,
    trending: false,
    recommended: true,
    verified: true,
    storageSize: 45_000_000,
    trendingScore: 60,
    developer: { slug: 'gulf-studios', name: 'Gulf Studios', verified: false },
    isSystemApp: true,
  },
];

export async function seedGulfStore(): Promise<{ apps: number; developers: number; reviews: number; packages: number }> {
  let developerCount = 0;
  const developerMap = new Map<string, string>();

  for (const appData of STORE_APPS) {
    const devKey = appData.developer.slug;
    if (!developerMap.has(devKey)) {
      const dev = await Developer.findOneAndUpdate(
        { slug: devKey },
        {
          slug: devKey,
          name: appData.developer.name,
          description: `Official developer for ${appData.developer.name}`,
          logo: '🏬',
          verified: appData.developer.verified,
        },
        { upsert: true, new: true }
      );
      developerMap.set(devKey, dev._id.toString());
      developerCount++;
    }

    const app = await App.findOneAndUpdate(
      { bundleId: appData.bundleId },
      {
        bundleId: appData.bundleId,
        name: appData.name,
        version: appData.version,
        description: appData.description,
        icon: appData.icon,
        category: appData.category,
        permissions: appData.permissions,
        isSystemApp: (appData as { isSystemApp?: boolean }).isSystemApp ?? false,
        isPublished: true,
      },
      { upsert: true, new: true }
    );

    await StoreListing.findOneAndUpdate(
      { bundleId: appData.bundleId },
      {
        appId: app._id,
        bundleId: appData.bundleId,
        developerId: developerMap.get(devKey),
        tagline: appData.tagline,
        longDescription: appData.longDescription,
        screenshots: appData.screenshots,
        featured: appData.featured ?? false,
        trending: appData.trending ?? false,
        editorsChoice: appData.editorsChoice ?? false,
        recommended: appData.recommended ?? false,
        verified: appData.verified ?? false,
        premium: appData.premium ?? false,
        price: appData.price ?? 0,
        storageSize: appData.storageSize,
        category: appData.category,
        permissions: appData.permissions,
        trendingScore: appData.trendingScore,
        tags: [appData.category, appData.name.toLowerCase()],
        ratingAverage: 4.2 + Math.random() * 0.7,
        ratingCount: Math.floor(Math.random() * 500) + 50,
        downloadCount: Math.floor(Math.random() * 10000) + 1000,
      },
      { upsert: true, new: true }
    );

    await AppVersion.findOneAndUpdate(
      { bundleId: appData.bundleId, version: appData.version },
      {
        appId: app._id,
        bundleId: appData.bundleId,
        version: appData.version,
        changelog: `Initial release of ${appData.name}`,
        size: appData.storageSize,
      },
      { upsert: true }
    );
  }

  // Sample reviews for bank app
  const bankListing = await StoreListing.findOne({ bundleId: 'com.gulfos.bank' });
  if (bankListing) {
    const sampleReviews = [
      { username: 'alex_b', rating: 5, title: 'Best mobile bank', body: 'Incredibly smooth transfers and beautiful UI.' },
      { username: 'maria_k', rating: 4, title: 'Great features', body: 'QR payments work flawlessly. Would love more analytics.' },
      { username: 'john_d', rating: 5, title: 'Premium experience', body: 'Feels like a real bank app. Security is top notch.' },
    ];

    for (const r of sampleReviews) {
      await StoreReview.findOneAndUpdate(
        { bundleId: 'com.gulfos.bank', username: r.username },
        {
          listingId: bankListing._id,
          bundleId: 'com.gulfos.bank',
          userId: bankListing._id,
          ...r,
        },
        { upsert: true }
      );
    }
  }

  await Developer.updateMany({}, [{ $set: { appCount: 0 } }]);
  for (const [slug, id] of developerMap) {
    const count = STORE_APPS.filter((a) => a.developer.slug === slug).length;
    await Developer.findByIdAndUpdate(id, { appCount: count });
  }

  return {
    apps: STORE_APPS.length,
    developers: developerMap.size,
    reviews: 3,
    packages: await (async () => {
      const { seedAllPackages } = await import('./packageService');
      return seedAllPackages();
    })(),
  };
}
