import type { UserSettings } from '@/types';

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'dark',
  accentColor: 'gold',
  wallpaper: {
    id: 'gulf-gradient',
    type: 'animated',
    animatedClass: 'wallpaper-gulf',
    dark: 'radial-gradient(120% 90% at 80% -10%, #3d2f0e 0%, transparent 50%), radial-gradient(120% 100% at 15% 110%, #14233f 0%, transparent 55%), linear-gradient(160deg, #000000 0%, #0b0f1d 35%, #1a2340 62%, #2c2410 100%)',
    light: 'radial-gradient(110% 80% at 85% -5%, #f6dfa4 0%, transparent 55%), radial-gradient(120% 100% at 10% 110%, #a8c4ec 0%, transparent 60%), linear-gradient(160deg, #dfe8f4 0%, #cdd8ec 40%, #e8d9b0 100%)',
  },
  language: 'en',
  region: 'US',
  timezone: 'America/Los_Angeles',
  dateFormat: 'mdy',
  timeFormat: '24h',
  temperatureUnit: 'celsius',
  distanceUnit: 'km',
  currency: 'USD',
  keyboardLayout: 'qwerty',
  reduceMotion: false,
  highContrast: false,
  fontSize: 'medium',
  hapticsEnabled: true,
  soundsEnabled: true,
  brightness: 80,
  volume: 70,
  wifiEnabled: true,
  bluetoothEnabled: false,
  silentMode: false,
  rotationLock: false,
  flashlightEnabled: false,
  autoTheme: true,
  displayZoom: 'default',
  animationsEnabled: true,
  autoBrightness: false,
  refreshRate: 60,
  screenTimeout: 60,
  alwaysOnDisplay: false,
  mediaVolume: 70,
  callVolume: 80,
  notificationVolume: 70,
  alarmVolume: 90,
  vibrationEnabled: true,
  ringtone: 'default',
  notificationSound: 'default',
  keyboardSound: true,
  mobileDataEnabled: true,
  hotspotEnabled: false,
  airplaneMode: false,
  powerSavingMode: false,
  lowPowerMode: false,
  voiceOverEnabled: false,
  largeText: false,
  boldText: false,
  colorFilters: false,
  monoAudio: false,
  touchAssistance: false,
  developerModeEnabled: false,
  twoFactorEnabled: false,
  appLockEnabled: false,
};
