import type { UserSettings } from '@/types';

export const DEFAULT_SETTINGS: UserSettings = {
  theme: 'dark',
  accentColor: 'gold',
  wallpaper: {
    id: 'gulf-gradient',
    type: 'animated',
    animatedClass: 'wallpaper-gulf',
    dark: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #16213e 100%)',
    light: 'linear-gradient(135deg, #f5f5f5 0%, #e8e8e8 50%, #d4d4d4 100%)',
  },
  language: 'en',
  region: 'US',
  timezone: 'America/Los_Angeles',
  dateFormat: 'mdy',
  timeFormat: '24h',
  temperatureUnit: 'celsius',
  distanceUnit: 'km',
  currency: 'USD',
  keyboardLayout: 'qwerty',
  reduceMotion: false,
  highContrast: false,
  fontSize: 'medium',
  hapticsEnabled: true,
  soundsEnabled: true,
  brightness: 80,
  volume: 70,
  wifiEnabled: true,
  bluetoothEnabled: false,
  silentMode: false,
  rotationLock: false,
  flashlightEnabled: false,
  autoTheme: true,
  displayZoom: 'default',
  animationsEnabled: true,
  autoBrightness: false,
  refreshRate: 60,
  screenTimeout: 60,
  alwaysOnDisplay: false,
  mediaVolume: 70,
  callVolume: 80,
  notificationVolume: 70,
  alarmVolume: 90,
  vibrationEnabled: true,
  ringtone: 'default',
  notificationSound: 'default',
  keyboardSound: true,
  mobileDataEnabled: true,
  hotspotEnabled: false,
  airplaneMode: false,
  powerSavingMode: false,
  lowPowerMode: false,
  voiceOverEnabled: false,
  largeText: false,
  boldText: false,
  colorFilters: false,
  monoAudio: false,
  touchAssistance: false,
  developerModeEnabled: false,
  twoFactorEnabled: false,
  appLockEnabled: false,
};
