/** API mount paths that require phone presence validation before any action */

export const PHONE_GUARDED_API_PREFIXES = [
  '/api/phone',
  '/api/contacts',
  '/api/messages',
  '/api/mail',
  '/api/sim',
  '/api/bank',
  '/api/identity',
  '/api/device',
  '/api/filesystem',
  '/api/settings',
  '/api/apps',
  '/api/system-apps',
  '/api/communication',
  '/api/notifications',
  '/api/store',
  '/api/browser',
  '/api/chat',
  '/api/personalization',
  '/api/security',
  '/api/privacy',
  '/api/cloud',
  '/api/find-my',
  '/api/updates',
  '/api/assistant',
  '/api/automation',
  '/api/shortcuts',
  '/api/focus',
  '/api/intelligence',
  '/api/diagnostics',
  '/api/analytics',
  '/api/developer',
  '/api/enterprise',
  '/api/system',
] as const;

/** Client → server socket events that require an active phone */
export const PHONE_INTERACTIVE_SOCKET_EVENTS = new Set([
  'phone:open',
  'phone:app:open',
  'phone:action',
  'message:send',
  'call:initiate',
  'call:answer',
  'contacts:open',
  'camera:capture',
  'gallery:open',
  'files:open',
  'mail:send',
  'bank:action',
  'maps:open',
  'notes:open',
  'settings:open',
  'identity:open',
]);
