import type { TranslationDict } from '../types';
import { en } from './en';

/** Deep-merge locale overrides onto English fallback */
function mergeLocale(overrides: Partial<TranslationDict>): TranslationDict {
  return {
    common: { ...en.common, ...overrides.common },
    settings: { ...en.settings, ...overrides.settings },
  };
}

export const fr = mergeLocale({
  common: { back: 'Retour', settings: 'Réglages', on: 'Activé', off: 'Désactivé', enabled: 'Activé', disabled: 'Désactivé', loading: 'Chargement…', save: 'Enregistrer', reset: 'Réinitialiser', cancel: 'Annuler', confirm: 'Confirmer' },
  settings: { title: 'Réglages', appearance: 'Apparence', general: 'Général', display: 'Affichage', sound: 'Son', soundHaptics: 'Son et retour haptique', network: 'Réseau', privacy: 'Confidentialité', privacySecurity: 'Confidentialité et sécurité', security: 'Sécurité', battery: 'Batterie', storage: 'Stockage', apps: 'Applications', accessibility: 'Accessibilité', developer: 'Développeur', about: 'À propos', device: 'Appareil', system: 'Système', theme: 'Thème', wallpaper: 'Fond d\'écran', accentColor: 'Couleur d\'accentuation', language: 'Langue', region: 'Région', timezone: 'Fuseau horaire', dateFormat: 'Format de date', timeFormat: 'Format de l\'heure', temperatureUnit: 'Unité de température', distanceUnit: 'Unité de distance', currency: 'Devise', keyboardLayout: 'Disposition du clavier', brightness: 'Luminosité', fontSize: 'Taille de police', autoTheme: 'Thème automatique', displayZoom: 'Zoom d\'affichage', animations: 'Animations', reduceMotion: 'Réduire les animations', autoBrightness: 'Luminosité automatique', refreshRate: 'Fréquence de rafraîchissement', screenTimeout: 'Délai d\'extinction', alwaysOnDisplay: 'Toujours actif', sounds: 'Sons', haptics: 'Retour haptique', mediaVolume: 'Volume média', callVolume: 'Volume appels', notificationVolume: 'Volume notifications', alarmVolume: 'Volume alarme', vibration: 'Vibration', ringtone: 'Sonnerie', notificationSound: 'Son de notification', keyboardSound: 'Son du clavier', wifi: 'Wi-Fi', mobileData: 'Données mobiles', bluetooth: 'Bluetooth', airplaneMode: 'Mode avion', hotspot: 'Point d\'accès', vpn: 'VPN', permissions: 'Autorisations', highContrast: 'Contraste élevé', voiceOver: 'VoiceOver', largeText: 'Texte agrandi', boldText: 'Texte en gras', colorFilters: 'Filtres de couleur', monoAudio: 'Audio mono', touchAssistance: 'Assistance tactile', powerSaving: 'Économie d\'énergie', lowPowerMode: 'Mode économie', installedApps: 'Applications installées', aboutDevice: 'À propos de l\'appareil', model: 'Modèle', manufacturer: 'Fabricant', developerName: 'Développeur', operatingSystem: 'Système d\'exploitation', kernel: 'Noyau', buildNumber: 'Numéro de build', version: 'Version', serialNumber: 'Numéro de série', deviceUuid: 'UUID de l\'appareil', storageLabel: 'Stockage', ram: 'RAM', cpu: 'Processeur', gpu: 'GPU', batteryHealth: 'État de la batterie', imei: 'IMEI', small: 'Petit', medium: 'Moyen', large: 'Grand', light: 'Clair', dark: 'Sombre', systemTheme: 'Système', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Kilomètres', miles: 'Miles', format12h: '12 heures', format24h: '24 heures', seconds: 'secondes', minutes: 'minutes' },
});

export const de = mergeLocale({
  common: { back: 'Zurück', settings: 'Einstellungen', on: 'Ein', off: 'Aus', enabled: 'Aktiviert', disabled: 'Deaktiviert', loading: 'Laden…', save: 'Speichern', reset: 'Zurücksetzen', cancel: 'Abbrechen', confirm: 'Bestätigen' },
  settings: { title: 'Einstellungen', appearance: 'Erscheinungsbild', general: 'Allgemein', display: 'Anzeige', sound: 'Ton', soundHaptics: 'Ton & Haptik', network: 'Netzwerk', privacy: 'Datenschutz', privacySecurity: 'Datenschutz & Sicherheit', security: 'Sicherheit', battery: 'Batterie', storage: 'Speicher', apps: 'Apps', accessibility: 'Bedienungshilfen', developer: 'Entwickler', about: 'Info', device: 'Gerät', system: 'System', theme: 'Design', wallpaper: 'Hintergrundbild', accentColor: 'Akzentfarbe', language: 'Sprache', region: 'Region', timezone: 'Zeitzone', dateFormat: 'Datumsformat', timeFormat: 'Zeitformat', temperatureUnit: 'Temperatureinheit', distanceUnit: 'Entfernungseinheit', currency: 'Währung', keyboardLayout: 'Tastaturlayout', brightness: 'Helligkeit', fontSize: 'Schriftgröße', autoTheme: 'Automatisches Design', displayZoom: 'Anzeigezoom', animations: 'Animationen', reduceMotion: 'Bewegung reduzieren', autoBrightness: 'Automatische Helligkeit', refreshRate: 'Bildwiederholrate', screenTimeout: 'Bildschirmzeitlimit', alwaysOnDisplay: 'Immer eingeschaltet', sounds: 'Töne', haptics: 'Haptik', mediaVolume: 'Medienlautstärke', callVolume: 'Anruflautstärke', notificationVolume: 'Benachrichtigungslautstärke', alarmVolume: 'Alarmlautstärke', vibration: 'Vibration', ringtone: 'Klingelton', notificationSound: 'Benachrichtigungston', keyboardSound: 'Tastaturton', wifi: 'WLAN', mobileData: 'Mobilfunkdaten', bluetooth: 'Bluetooth', airplaneMode: 'Flugmodus', hotspot: 'Hotspot', vpn: 'VPN', permissions: 'Berechtigungen', highContrast: 'Hoher Kontrast', voiceOver: 'VoiceOver', largeText: 'Großer Text', boldText: 'Fetter Text', colorFilters: 'Farbfilter', monoAudio: 'Mono-Audio', touchAssistance: 'Berührungshilfe', powerSaving: 'Energiesparmodus', lowPowerMode: 'Niedriger Energiemodus', installedApps: 'Installierte Apps', aboutDevice: 'Über das Gerät', model: 'Modell', manufacturer: 'Hersteller', developerName: 'Entwickler', operatingSystem: 'Betriebssystem', kernel: 'Kernel', buildNumber: 'Build-Nummer', version: 'Version', serialNumber: 'Seriennummer', deviceUuid: 'Geräte-UUID', storageLabel: 'Speicher', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'Batteriezustand', imei: 'IMEI', small: 'Klein', medium: 'Mittel', large: 'Groß', light: 'Hell', dark: 'Dunkel', systemTheme: 'System', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Kilometer', miles: 'Meilen', format12h: '12-Stunden', format24h: '24-Stunden', seconds: 'Sekunden', minutes: 'Minuten' },
});

export const es = mergeLocale({
  common: { back: 'Atrás', settings: 'Ajustes', on: 'Activado', off: 'Desactivado', enabled: 'Activado', disabled: 'Desactivado', loading: 'Cargando…', save: 'Guardar', reset: 'Restablecer', cancel: 'Cancelar', confirm: 'Confirmar' },
  settings: { title: 'Ajustes', appearance: 'Apariencia', general: 'General', display: 'Pantalla', sound: 'Sonido', soundHaptics: 'Sonido y háptica', network: 'Red', privacy: 'Privacidad', privacySecurity: 'Privacidad y seguridad', security: 'Seguridad', battery: 'Batería', storage: 'Almacenamiento', apps: 'Apps', accessibility: 'Accesibilidad', developer: 'Desarrollador', about: 'Acerca de', device: 'Dispositivo', system: 'Sistema', theme: 'Tema', wallpaper: 'Fondo de pantalla', accentColor: 'Color de acento', language: 'Idioma', region: 'Región', timezone: 'Zona horaria', dateFormat: 'Formato de fecha', timeFormat: 'Formato de hora', temperatureUnit: 'Unidad de temperatura', distanceUnit: 'Unidad de distancia', currency: 'Moneda', keyboardLayout: 'Distribución del teclado', brightness: 'Brillo', fontSize: 'Tamaño de fuente', autoTheme: 'Tema automático', displayZoom: 'Zoom de pantalla', animations: 'Animaciones', reduceMotion: 'Reducir movimiento', autoBrightness: 'Brillo automático', refreshRate: 'Frecuencia de actualización', screenTimeout: 'Tiempo de pantalla', alwaysOnDisplay: 'Pantalla siempre activa', sounds: 'Sonidos', haptics: 'Háptica', mediaVolume: 'Volumen de medios', callVolume: 'Volumen de llamadas', notificationVolume: 'Volumen de notificaciones', alarmVolume: 'Volumen de alarma', vibration: 'Vibración', ringtone: 'Tono de llamada', notificationSound: 'Sonido de notificación', keyboardSound: 'Sonido del teclado', wifi: 'Wi-Fi', mobileData: 'Datos móviles', bluetooth: 'Bluetooth', airplaneMode: 'Modo avión', hotspot: 'Punto de acceso', vpn: 'VPN', permissions: 'Permisos', highContrast: 'Alto contraste', voiceOver: 'VoiceOver', largeText: 'Texto grande', boldText: 'Texto en negrita', colorFilters: 'Filtros de color', monoAudio: 'Audio mono', touchAssistance: 'Asistencia táctil', powerSaving: 'Ahorro de energía', lowPowerMode: 'Modo de bajo consumo', installedApps: 'Apps instaladas', aboutDevice: 'Acerca del dispositivo', model: 'Modelo', manufacturer: 'Fabricante', developerName: 'Desarrollador', operatingSystem: 'Sistema operativo', kernel: 'Kernel', buildNumber: 'Número de compilación', version: 'Versión', serialNumber: 'Número de serie', deviceUuid: 'UUID del dispositivo', storageLabel: 'Almacenamiento', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'Salud de la batería', imei: 'IMEI', small: 'Pequeño', medium: 'Mediano', large: 'Grande', light: 'Claro', dark: 'Oscuro', systemTheme: 'Sistema', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Kilómetros', miles: 'Millas', format12h: '12 horas', format24h: '24 horas', seconds: 'segundos', minutes: 'minutos' },
});

export const it = mergeLocale({
  common: { back: 'Indietro', settings: 'Impostazioni', on: 'Attivo', off: 'Disattivo', enabled: 'Attivato', disabled: 'Disattivato', loading: 'Caricamento…', save: 'Salva', reset: 'Reimposta', cancel: 'Annulla', confirm: 'Conferma' },
  settings: { title: 'Impostazioni', appearance: 'Aspetto', general: 'Generale', display: 'Schermo', sound: 'Suono', soundHaptics: 'Suono e feedback aptico', network: 'Rete', privacy: 'Privacy', privacySecurity: 'Privacy e sicurezza', security: 'Sicurezza', battery: 'Batteria', storage: 'Archiviazione', apps: 'App', accessibility: 'Accessibilità', developer: 'Sviluppatore', about: 'Info', device: 'Dispositivo', system: 'Sistema', theme: 'Tema', wallpaper: 'Sfondo', accentColor: 'Colore di accento', language: 'Lingua', region: 'Regione', timezone: 'Fuso orario', dateFormat: 'Formato data', timeFormat: 'Formato ora', temperatureUnit: 'Unità temperatura', distanceUnit: 'Unità distanza', currency: 'Valuta', keyboardLayout: 'Layout tastiera', brightness: 'Luminosità', fontSize: 'Dimensione testo', autoTheme: 'Tema automatico', displayZoom: 'Zoom schermo', animations: 'Animazioni', reduceMotion: 'Riduci movimento', autoBrightness: 'Luminosità automatica', refreshRate: 'Frequenza aggiornamento', screenTimeout: 'Timeout schermo', alwaysOnDisplay: 'Schermo sempre attivo', sounds: 'Suoni', haptics: 'Feedback aptico', mediaVolume: 'Volume media', callVolume: 'Volume chiamate', notificationVolume: 'Volume notifiche', alarmVolume: 'Volume sveglia', vibration: 'Vibrazione', ringtone: 'Suoneria', notificationSound: 'Suono notifica', keyboardSound: 'Suono tastiera', wifi: 'Wi-Fi', mobileData: 'Dati mobili', bluetooth: 'Bluetooth', airplaneMode: 'Modalità aereo', hotspot: 'Hotspot', vpn: 'VPN', permissions: 'Autorizzazioni', highContrast: 'Contrasto elevato', voiceOver: 'VoiceOver', largeText: 'Testo grande', boldText: 'Testo grassetto', colorFilters: 'Filtri colore', monoAudio: 'Audio mono', touchAssistance: 'Assistenza touch', powerSaving: 'Risparmio energetico', lowPowerMode: 'Modalità risparmio', installedApps: 'App installate', aboutDevice: 'Info dispositivo', model: 'Modello', manufacturer: 'Produttore', developerName: 'Sviluppatore', operatingSystem: 'Sistema operativo', kernel: 'Kernel', buildNumber: 'Numero build', version: 'Versione', serialNumber: 'Numero di serie', deviceUuid: 'UUID dispositivo', storageLabel: 'Archiviazione', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'Salute batteria', imei: 'IMEI', small: 'Piccolo', medium: 'Medio', large: 'Grande', light: 'Chiaro', dark: 'Scuro', systemTheme: 'Sistema', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Chilometri', miles: 'Miglia', format12h: '12 ore', format24h: '24 ore', seconds: 'secondi', minutes: 'minuti' },
});

export const pt = mergeLocale({
  common: { back: 'Voltar', settings: 'Configurações', on: 'Ativado', off: 'Desativado', enabled: 'Ativado', disabled: 'Desativado', loading: 'Carregando…', save: 'Salvar', reset: 'Redefinir', cancel: 'Cancelar', confirm: 'Confirmar' },
  settings: { title: 'Configurações', appearance: 'Aparência', general: 'Geral', display: 'Tela', sound: 'Som', soundHaptics: 'Som e háptica', network: 'Rede', privacy: 'Privacidade', privacySecurity: 'Privacidade e segurança', security: 'Segurança', battery: 'Bateria', storage: 'Armazenamento', apps: 'Apps', accessibility: 'Acessibilidade', developer: 'Desenvolvedor', about: 'Sobre', device: 'Dispositivo', system: 'Sistema', theme: 'Tema', wallpaper: 'Papel de parede', accentColor: 'Cor de destaque', language: 'Idioma', region: 'Região', timezone: 'Fuso horário', dateFormat: 'Formato de data', timeFormat: 'Formato de hora', temperatureUnit: 'Unidade de temperatura', distanceUnit: 'Unidade de distância', currency: 'Moeda', keyboardLayout: 'Layout do teclado', brightness: 'Brilho', fontSize: 'Tamanho da fonte', autoTheme: 'Tema automático', displayZoom: 'Zoom da tela', animations: 'Animações', reduceMotion: 'Reduzir movimento', autoBrightness: 'Brilho automático', refreshRate: 'Taxa de atualização', screenTimeout: 'Tempo de tela', alwaysOnDisplay: 'Tela sempre ativa', sounds: 'Sons', haptics: 'Háptica', mediaVolume: 'Volume de mídia', callVolume: 'Volume de chamadas', notificationVolume: 'Volume de notificações', alarmVolume: 'Volume do alarme', vibration: 'Vibração', ringtone: 'Toque', notificationSound: 'Som de notificação', keyboardSound: 'Som do teclado', wifi: 'Wi-Fi', mobileData: 'Dados móveis', bluetooth: 'Bluetooth', airplaneMode: 'Modo avião', hotspot: 'Ponto de acesso', vpn: 'VPN', permissions: 'Permissões', highContrast: 'Alto contraste', voiceOver: 'VoiceOver', largeText: 'Texto grande', boldText: 'Texto em negrito', colorFilters: 'Filtros de cor', monoAudio: 'Áudio mono', touchAssistance: 'Assistência de toque', powerSaving: 'Economia de energia', lowPowerMode: 'Modo de baixo consumo', installedApps: 'Apps instalados', aboutDevice: 'Sobre o dispositivo', model: 'Modelo', manufacturer: 'Fabricante', developerName: 'Desenvolvedor', operatingSystem: 'Sistema operacional', kernel: 'Kernel', buildNumber: 'Número da build', version: 'Versão', serialNumber: 'Número de série', deviceUuid: 'UUID do dispositivo', storageLabel: 'Armazenamento', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'Saúde da bateria', imei: 'IMEI', small: 'Pequeno', medium: 'Médio', large: 'Grande', light: 'Claro', dark: 'Escuro', systemTheme: 'Sistema', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Quilômetros', miles: 'Milhas', format12h: '12 horas', format24h: '24 horas', seconds: 'segundos', minutes: 'minutos' },
});

export const tr = mergeLocale({
  common: { back: 'Geri', settings: 'Ayarlar', on: 'Açık', off: 'Kapalı', enabled: 'Etkin', disabled: 'Devre dışı', loading: 'Yükleniyor…', save: 'Kaydet', reset: 'Sıfırla', cancel: 'İptal', confirm: 'Onayla' },
  settings: { title: 'Ayarlar', appearance: 'Görünüm', general: 'Genel', display: 'Ekran', sound: 'Ses', soundHaptics: 'Ses ve dokunsal', network: 'Ağ', privacy: 'Gizlilik', privacySecurity: 'Gizlilik ve güvenlik', security: 'Güvenlik', battery: 'Pil', storage: 'Depolama', apps: 'Uygulamalar', accessibility: 'Erişilebilirlik', developer: 'Geliştirici', about: 'Hakkında', device: 'Cihaz', system: 'Sistem', theme: 'Tema', wallpaper: 'Duvar kağıdı', accentColor: 'Vurgu rengi', language: 'Dil', region: 'Bölge', timezone: 'Saat dilimi', dateFormat: 'Tarih biçimi', timeFormat: 'Saat biçimi', temperatureUnit: 'Sıcaklık birimi', distanceUnit: 'Mesafe birimi', currency: 'Para birimi', keyboardLayout: 'Klavye düzeni', brightness: 'Parlaklık', fontSize: 'Yazı boyutu', autoTheme: 'Otomatik tema', displayZoom: 'Ekran yakınlaştırma', animations: 'Animasyonlar', reduceMotion: 'Hareketi azalt', autoBrightness: 'Otomatik parlaklık', refreshRate: 'Yenileme hızı', screenTimeout: 'Ekran zaman aşımı', alwaysOnDisplay: 'Her zaman açık ekran', sounds: 'Sesler', haptics: 'Dokunsal', mediaVolume: 'Medya sesi', callVolume: 'Arama sesi', notificationVolume: 'Bildirim sesi', alarmVolume: 'Alarm sesi', vibration: 'Titreşim', ringtone: 'Zil sesi', notificationSound: 'Bildirim sesi', keyboardSound: 'Klavye sesi', wifi: 'Wi-Fi', mobileData: 'Mobil veri', bluetooth: 'Bluetooth', airplaneMode: 'Uçak modu', hotspot: 'Erişim noktası', vpn: 'VPN', permissions: 'İzinler', highContrast: 'Yüksek kontrast', voiceOver: 'VoiceOver', largeText: 'Büyük metin', boldText: 'Kalın metin', colorFilters: 'Renk filtreleri', monoAudio: 'Mono ses', touchAssistance: 'Dokunma yardımı', powerSaving: 'Güç tasarrufu', lowPowerMode: 'Düşük güç modu', installedApps: 'Yüklü uygulamalar', aboutDevice: 'Cihaz hakkında', model: 'Model', manufacturer: 'Üretici', developerName: 'Geliştirici', operatingSystem: 'İşletim sistemi', kernel: 'Çekirdek', buildNumber: 'Derleme numarası', version: 'Sürüm', serialNumber: 'Seri numarası', deviceUuid: 'Cihaz UUID', storageLabel: 'Depolama', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'Pil sağlığı', imei: 'IMEI', small: 'Küçük', medium: 'Orta', large: 'Büyük', light: 'Açık', dark: 'Koyu', systemTheme: 'Sistem', celsius: 'Celsius', fahrenheit: 'Fahrenheit', kilometers: 'Kilometre', miles: 'Mil', format12h: '12 saat', format24h: '24 saat', seconds: 'saniye', minutes: 'dakika' },
});

export const ru = mergeLocale({
  common: { back: 'Назад', settings: 'Настройки', on: 'Вкл', off: 'Выкл', enabled: 'Включено', disabled: 'Отключено', loading: 'Загрузка…', save: 'Сохранить', reset: 'Сбросить', cancel: 'Отмена', confirm: 'Подтвердить' },
  settings: { title: 'Настройки', appearance: 'Оформление', general: 'Основные', display: 'Экран', sound: 'Звук', soundHaptics: 'Звук и тактильность', network: 'Сеть', privacy: 'Конфиденциальность', privacySecurity: 'Конфиденциальность и безопасность', security: 'Безопасность', battery: 'Батарея', storage: 'Хранилище', apps: 'Приложения', accessibility: 'Универсальный доступ', developer: 'Разработчик', about: 'О системе', device: 'Устройство', system: 'Система', theme: 'Тема', wallpaper: 'Обои', accentColor: 'Акцентный цвет', language: 'Язык', region: 'Регион', timezone: 'Часовой пояс', dateFormat: 'Формат даты', timeFormat: 'Формат времени', temperatureUnit: 'Единица температуры', distanceUnit: 'Единица расстояния', currency: 'Валюта', keyboardLayout: 'Раскладка клавиатуры', brightness: 'Яркость', fontSize: 'Размер шрифта', autoTheme: 'Автоматическая тема', displayZoom: 'Масштаб экрана', animations: 'Анимации', reduceMotion: 'Уменьшить движение', autoBrightness: 'Автояркость', refreshRate: 'Частота обновления', screenTimeout: 'Тайм-аут экрана', alwaysOnDisplay: 'Всегда включённый экран', sounds: 'Звуки', haptics: 'Тактильность', mediaVolume: 'Громкость медиа', callVolume: 'Громкость звонков', notificationVolume: 'Громкость уведомлений', alarmVolume: 'Громкость будильника', vibration: 'Вибрация', ringtone: 'Мелодия', notificationSound: 'Звук уведомления', keyboardSound: 'Звук клавиатуры', wifi: 'Wi-Fi', mobileData: 'Мобильные данные', bluetooth: 'Bluetooth', airplaneMode: 'Режим полёта', hotspot: 'Точка доступа', vpn: 'VPN', permissions: 'Разрешения', highContrast: 'Высокий контраст', voiceOver: 'VoiceOver', largeText: 'Крупный текст', boldText: 'Жирный текст', colorFilters: 'Цветовые фильтры', monoAudio: 'Моно звук', touchAssistance: 'Помощь касанием', powerSaving: 'Энергосбережение', lowPowerMode: 'Режим низкого энергопотребления', installedApps: 'Установленные приложения', aboutDevice: 'Об устройстве', model: 'Модель', manufacturer: 'Производитель', developerName: 'Разработчик', operatingSystem: 'Операционная система', kernel: 'Ядро', buildNumber: 'Номер сборки', version: 'Версия', serialNumber: 'Серийный номер', deviceUuid: 'UUID устройства', storageLabel: 'Хранилище', ram: 'ОЗУ', cpu: 'Процессор', gpu: 'Графика', batteryHealth: 'Состояние батареи', imei: 'IMEI', small: 'Маленький', medium: 'Средний', large: 'Большой', light: 'Светлая', dark: 'Тёмная', systemTheme: 'Системная', celsius: 'Цельсий', fahrenheit: 'Фаренгейт', kilometers: 'Километры', miles: 'Мили', format12h: '12 часов', format24h: '24 часа', seconds: 'секунды', minutes: 'минуты' },
});

export const ja = mergeLocale({
  common: { back: '戻る', settings: '設定', on: 'オン', off: 'オフ', enabled: '有効', disabled: '無効', loading: '読み込み中…', save: '保存', reset: 'リセット', cancel: 'キャンセル', confirm: '確認' },
  settings: { title: '設定', appearance: '外観', general: '一般', display: 'ディスプレイ', sound: 'サウンド', soundHaptics: 'サウンドと触覚', network: 'ネットワーク', privacy: 'プライバシー', privacySecurity: 'プライバシーとセキュリティ', security: 'セキュリティ', battery: 'バッテリー', storage: 'ストレージ', apps: 'アプリ', accessibility: 'アクセシビリティ', developer: '開発者', about: '情報', device: 'デバイス', system: 'システム', theme: 'テーマ', wallpaper: '壁紙', accentColor: 'アクセントカラー', language: '言語', region: '地域', timezone: 'タイムゾーン', dateFormat: '日付形式', timeFormat: '時刻形式', temperatureUnit: '温度単位', distanceUnit: '距離単位', currency: '通貨', keyboardLayout: 'キーボードレイアウト', brightness: '明るさ', fontSize: 'フォントサイズ', autoTheme: '自動テーマ', displayZoom: '表示ズーム', animations: 'アニメーション', reduceMotion: '動きを減らす', autoBrightness: '自動明るさ', refreshRate: 'リフレッシュレート', screenTimeout: '画面タイムアウト', alwaysOnDisplay: '常時表示', sounds: 'サウンド', haptics: '触覚', mediaVolume: 'メディア音量', callVolume: '通話音量', notificationVolume: '通知音量', alarmVolume: 'アラーム音量', vibration: 'バイブレーション', ringtone: '着信音', notificationSound: '通知音', keyboardSound: 'キーボード音', wifi: 'Wi-Fi', mobileData: 'モバイルデータ', bluetooth: 'Bluetooth', airplaneMode: '機内モード', hotspot: 'ホットスポット', vpn: 'VPN', permissions: '権限', highContrast: '高コントラスト', voiceOver: 'VoiceOver', largeText: '大きな文字', boldText: '太字', colorFilters: 'カラーフィルタ', monoAudio: 'モノラル音声', touchAssistance: 'タッチ補助', powerSaving: '省電力', lowPowerMode: '低電力モード', installedApps: 'インストール済みアプリ', aboutDevice: 'デバイス情報', model: 'モデル', manufacturer: 'メーカー', developerName: '開発者', operatingSystem: 'オペレーティングシステム', kernel: 'カーネル', buildNumber: 'ビルド番号', version: 'バージョン', serialNumber: 'シリアル番号', deviceUuid: 'デバイスUUID', storageLabel: 'ストレージ', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'バッテリー状態', imei: 'IMEI', small: '小', medium: '中', large: '大', light: 'ライト', dark: 'ダーク', systemTheme: 'システム', celsius: '摂氏', fahrenheit: '華氏', kilometers: 'キロメートル', miles: 'マイル', format12h: '12時間', format24h: '24時間', seconds: '秒', minutes: '分' },
});

export const zh = mergeLocale({
  common: { back: '返回', settings: '设置', on: '开', off: '关', enabled: '已启用', disabled: '已禁用', loading: '加载中…', save: '保存', reset: '重置', cancel: '取消', confirm: '确认' },
  settings: { title: '设置', appearance: '外观', general: '通用', display: '显示', sound: '声音', soundHaptics: '声音与触感', network: '网络', privacy: '隐私', privacySecurity: '隐私与安全', security: '安全', battery: '电池', storage: '存储', apps: '应用', accessibility: '辅助功能', developer: '开发者', about: '关于', device: '设备', system: '系统', theme: '主题', wallpaper: '壁纸', accentColor: '强调色', language: '语言', region: '地区', timezone: '时区', dateFormat: '日期格式', timeFormat: '时间格式', temperatureUnit: '温度单位', distanceUnit: '距离单位', currency: '货币', keyboardLayout: '键盘布局', brightness: '亮度', fontSize: '字体大小', autoTheme: '自动主题', displayZoom: '显示缩放', animations: '动画', reduceMotion: '减少动态效果', autoBrightness: '自动亮度', refreshRate: '刷新率', screenTimeout: '屏幕超时', alwaysOnDisplay: '始终显示', sounds: '声音', haptics: '触感', mediaVolume: '媒体音量', callVolume: '通话音量', notificationVolume: '通知音量', alarmVolume: '闹钟音量', vibration: '振动', ringtone: '铃声', notificationSound: '通知声音', keyboardSound: '键盘声音', wifi: 'Wi-Fi', mobileData: '移动数据', bluetooth: '蓝牙', airplaneMode: '飞行模式', hotspot: '热点', vpn: 'VPN', permissions: '权限', highContrast: '高对比度', voiceOver: '旁白', largeText: '大字体', boldText: '粗体', colorFilters: '色彩滤镜', monoAudio: '单声道音频', touchAssistance: '触控辅助', powerSaving: '省电模式', lowPowerMode: '低电量模式', installedApps: '已安装应用', aboutDevice: '关于本机', model: '型号', manufacturer: '制造商', developerName: '开发者', operatingSystem: '操作系统', kernel: '内核', buildNumber: '构建号', version: '版本', serialNumber: '序列号', deviceUuid: '设备UUID', storageLabel: '存储', ram: '内存', cpu: '处理器', gpu: '显卡', batteryHealth: '电池健康', imei: 'IMEI', small: '小', medium: '中', large: '大', light: '浅色', dark: '深色', systemTheme: '系统', celsius: '摄氏度', fahrenheit: '华氏度', kilometers: '公里', miles: '英里', format12h: '12小时', format24h: '24小时', seconds: '秒', minutes: '分钟' },
});

export const ko = mergeLocale({
  common: { back: '뒤로', settings: '설정', on: '켜짐', off: '꺼짐', enabled: '사용', disabled: '사용 안 함', loading: '로드 중…', save: '저장', reset: '재설정', cancel: '취소', confirm: '확인' },
  settings: { title: '설정', appearance: '모양', general: '일반', display: '디스플레이', sound: '사운드', soundHaptics: '사운드 및 햅틱', network: '네트워크', privacy: '개인 정보 보호', privacySecurity: '개인 정보 보호 및 보안', security: '보안', battery: '배터리', storage: '저장 공간', apps: '앱', accessibility: '손쉬운 사용', developer: '개발자', about: '정보', device: '기기', system: '시스템', theme: '테마', wallpaper: '배경화면', accentColor: '강조 색상', language: '언어', region: '지역', timezone: '시간대', dateFormat: '날짜 형식', timeFormat: '시간 형식', temperatureUnit: '온도 단위', distanceUnit: '거리 단위', currency: '통화', keyboardLayout: '키보드 레이아웃', brightness: '밝기', fontSize: '글자 크기', autoTheme: '자동 테마', displayZoom: '디스플레이 확대/축소', animations: '애니메이션', reduceMotion: '동작 줄이기', autoBrightness: '자동 밝기', refreshRate: '새로 고침 빈도', screenTimeout: '화면 시간 제한', alwaysOnDisplay: '항상 켜짐', sounds: '사운드', haptics: '햅틱', mediaVolume: '미디어 음량', callVolume: '통화 음량', notificationVolume: '알림 음량', alarmVolume: '알람 음량', vibration: '진동', ringtone: '벨소리', notificationSound: '알림 소리', keyboardSound: '키보드 소리', wifi: 'Wi-Fi', mobileData: '셀룰러 데이터', bluetooth: 'Bluetooth', airplaneMode: '비행기 모드', hotspot: '핫스팟', vpn: 'VPN', permissions: '권한', highContrast: '고대비', voiceOver: 'VoiceOver', largeText: '큰 텍스트', boldText: '굵은 텍스트', colorFilters: '색상 필터', monoAudio: '모노 오디오', touchAssistance: '터치 지원', powerSaving: '절전', lowPowerMode: '저전력 모드', installedApps: '설치된 앱', aboutDevice: '기기 정보', model: '모델', manufacturer: '제조사', developerName: '개발자', operatingSystem: '운영 체제', kernel: '커널', buildNumber: '빌드 번호', version: '버전', serialNumber: '일련번호', deviceUuid: '기기 UUID', storageLabel: '저장 공간', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: '배터리 상태', imei: 'IMEI', small: '작게', medium: '보통', large: '크게', light: '라이트', dark: '다크', systemTheme: '시스템', celsius: '섭씨', fahrenheit: '화씨', kilometers: '킬로미터', miles: '마일', format12h: '12시간', format24h: '24시간', seconds: '초', minutes: '분' },
});

export const hi = mergeLocale({
  common: { back: 'वापस', settings: 'सेटिंग्स', on: 'चालू', off: 'बंद', enabled: 'सक्षम', disabled: 'अक्षम', loading: 'लोड हो रहा है…', save: 'सहेजें', reset: 'रीसेट', cancel: 'रद्द करें', confirm: 'पुष्टि करें' },
  settings: { title: 'सेटिंग्स', appearance: 'दिखावट', general: 'सामान्य', display: 'डिस्प्ले', sound: 'ध्वनि', soundHaptics: 'ध्वनि और हैप्टिक', network: 'नेटवर्क', privacy: 'गोपनीयता', privacySecurity: 'गोपनीयता और सुरक्षा', security: 'सुरक्षा', battery: 'बैटरी', storage: 'स्टोरेज', apps: 'ऐप्स', accessibility: 'एक्सेसिबिलिटी', developer: 'डेवलपर', about: 'के बारे में', device: 'डिवाइस', system: 'सिस्टम', theme: 'थीम', wallpaper: 'वॉलपेपर', accentColor: 'एक्सेंट रंग', language: 'भाषा', region: 'क्षेत्र', timezone: 'समय क्षेत्र', dateFormat: 'तिथि प्रारूप', timeFormat: 'समय प्रारूप', temperatureUnit: 'तापमान इकाई', distanceUnit: 'दूरी इकाई', currency: 'मुद्रा', keyboardLayout: 'कीबोर्ड लेआउट', brightness: 'चमक', fontSize: 'फ़ॉन्ट आकार', autoTheme: 'स्वचालित थीम', displayZoom: 'डिस्प्ले ज़ूम', animations: 'एनिमेशन', reduceMotion: 'गति कम करें', autoBrightness: 'स्वचालित चमक', refreshRate: 'रिफ्रेश दर', screenTimeout: 'स्क्रीन टाइमआउट', alwaysOnDisplay: 'हमेशा चालू डिस्प्ले', sounds: 'ध्वनियाँ', haptics: 'हैप्टिक', mediaVolume: 'मीडिया वॉल्यूम', callVolume: 'कॉल वॉल्यूम', notificationVolume: 'सूचना वॉल्यूम', alarmVolume: 'अलार्म वॉल्यूम', vibration: 'कंपन', ringtone: 'रिंगटोन', notificationSound: 'सूचना ध्वनि', keyboardSound: 'कीबोर्ड ध्वनि', wifi: 'Wi-Fi', mobileData: 'मोबाइल डेटा', bluetooth: 'ब्लूटूथ', airplaneMode: 'एयरप्लेन मोड', hotspot: 'हॉटस्पॉट', vpn: 'VPN', permissions: 'अनुमतियाँ', highContrast: 'उच्च कंट्रास्ट', voiceOver: 'वॉयस ओवर', largeText: 'बड़ा टेक्स्ट', boldText: 'मोटा टेक्स्ट', colorFilters: 'रंग फ़िल्टर', monoAudio: 'मोनो ऑडियो', touchAssistance: 'स्पर्श सहायता', powerSaving: 'पावर सेविंग', lowPowerMode: 'लो पावर मोड', installedApps: 'इंस्टॉल किए गए ऐप्स', aboutDevice: 'डिवाइस के बारे में', model: 'मॉडल', manufacturer: 'निर्माता', developerName: 'डेवलपर', operatingSystem: 'ऑपरेटिंग सिस्टम', kernel: 'कर्नेल', buildNumber: 'बिल्ड नंबर', version: 'संस्करण', serialNumber: 'सीरियल नंबर', deviceUuid: 'डिवाइस UUID', storageLabel: 'स्टोरेज', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'बैटरी स्वास्थ्य', imei: 'IMEI', small: 'छोटा', medium: 'मध्यम', large: 'बड़ा', light: 'लाइट', dark: 'डार्क', systemTheme: 'सिस्टम', celsius: 'सेल्सियस', fahrenheit: 'फ़ारेनहाइट', kilometers: 'किलोमीटर', miles: 'मील', format12h: '12 घंटे', format24h: '24 घंटे', seconds: 'सेकंड', minutes: 'मिनट' },
});

export const ur = mergeLocale({
  common: { back: 'واپس', settings: 'ترتیبات', on: 'آن', off: 'آف', enabled: 'فعال', disabled: 'غیر فعال', loading: 'لوڈ ہو رہا ہے…', save: 'محفوظ کریں', reset: 'ری سیٹ', cancel: 'منسوخ', confirm: 'تصدیق' },
  settings: { title: 'ترتیبات', appearance: 'ظاہری شکل', general: 'عمومی', display: 'ڈسپلے', sound: 'آواز', soundHaptics: 'آواز اور ہیپٹک', network: 'نیٹ ورک', privacy: 'رازداری', privacySecurity: 'رازداری اور سیکیورٹی', security: 'سیکیورٹی', battery: 'بیٹری', storage: 'اسٹوریج', apps: 'ایپس', accessibility: 'رسائی', developer: 'ڈویلپر', about: 'کے بارے میں', device: 'ڈیوائس', system: 'سسٹم', theme: 'تھیم', wallpaper: 'وال پیپر', accentColor: 'ایکسنٹ رنگ', language: 'زبان', region: 'علاقہ', timezone: 'ٹائم زون', dateFormat: 'تاریخ کی شکل', timeFormat: 'وقت کی شکل', temperatureUnit: 'درجہ حرارت کی اکائی', distanceUnit: 'فاصلہ کی اکائی', currency: 'کرنسی', keyboardLayout: 'کی بورڈ لے آؤٹ', brightness: 'چمک', fontSize: 'فونٹ سائز', autoTheme: 'خودکار تھیم', displayZoom: 'ڈسپلے زوم', animations: 'اینیمیشن', reduceMotion: 'حرکت کم کریں', autoBrightness: 'خودکار چمک', refreshRate: 'ریفریش ریٹ', screenTimeout: 'اسکرین ٹائم آؤٹ', alwaysOnDisplay: 'ہمیشہ آن ڈسپلے', sounds: 'آوازیں', haptics: 'ہیپٹک', mediaVolume: 'میڈیا والیوم', callVolume: 'کال والیوم', notificationVolume: 'نوٹیفکیشن والیوم', alarmVolume: 'الارم والیوم', vibration: 'وائبریشن', ringtone: 'رنگ ٹون', notificationSound: 'نوٹیفکیشن آواز', keyboardSound: 'کی بورڈ آواز', wifi: 'وائی فائی', mobileData: 'موبائل ڈیٹا', bluetooth: 'بلوٹوتھ', airplaneMode: 'ہوائی جہاز موڈ', hotspot: 'ہاٹ سپاٹ', vpn: 'VPN', permissions: 'اجازتیں', highContrast: 'اعلی کنٹراسٹ', voiceOver: 'وائس اوور', largeText: 'بڑا متن', boldText: 'موٹا متن', colorFilters: 'رنگ فلٹر', monoAudio: 'مونو آڈیو', touchAssistance: 'ٹچ معاونت', powerSaving: 'بجلی بچت', lowPowerMode: 'کم پاور موڈ', installedApps: 'انسٹال شدہ ایپس', aboutDevice: 'ڈیوائس کے بارے میں', model: 'ماڈل', manufacturer: 'مینوفیکچرر', developerName: 'ڈویلپر', operatingSystem: 'آپریٹنگ سسٹم', kernel: 'کرنل', buildNumber: 'بلڈ نمبر', version: 'ورژن', serialNumber: 'سیریل نمبر', deviceUuid: 'ڈیوائس UUID', storageLabel: 'اسٹوریج', ram: 'RAM', cpu: 'CPU', gpu: 'GPU', batteryHealth: 'بیٹری صحت', imei: 'IMEI', small: 'چھوٹا', medium: 'درمیانہ', large: 'بڑا', light: 'لائٹ', dark: 'ڈارک', systemTheme: 'سسٹم', celsius: 'سیلسیس', fahrenheit: 'فارن ہائیٹ', kilometers: 'کلومیٹر', miles: 'میل', format12h: '12 گھنٹے', format24h: '24 گھنٹے', seconds: 'سیکنڈ', minutes: 'منٹ' },
});

export const fa = mergeLocale({
  common: { back: 'بازگشت', settings: 'تنظیمات', on: 'روشن', off: 'خاموش', enabled: 'فعال', disabled: 'غیرفعال', loading: 'در حال بارگذاری…', save: 'ذخیره', reset: 'بازنشانی', cancel: 'لغو', confirm: 'تأیید' },
  settings: { title: 'تنظیمات', appearance: 'ظاهر', general: 'عمومی', display: 'نمایشگر', sound: 'صدا', soundHaptics: 'صدا و لرزش', network: 'شبکه', privacy: 'حریم خصوصی', privacySecurity: 'حریم خصوصی و امنیت', security: 'امنیت', battery: 'باتری', storage: 'ذخیره‌سازی', apps: 'برنامه‌ها', accessibility: 'دسترسی‌پذیری', developer: 'توسعه‌دهنده', about: 'درباره', device: 'دستگاه', system: 'سیستم', theme: 'پوسته', wallpaper: 'تصویر پس‌زمینه', accentColor: 'رنگ تأکید', language: 'زبان', region: 'منطقه', timezone: 'منطقه زمانی', dateFormat: 'قالب تاریخ', timeFormat: 'قالب زمان', temperatureUnit: 'واحد دما', distanceUnit: 'واحد مسافت', currency: 'ارز', keyboardLayout: 'چیدمان صفحه‌کلید', brightness: 'روشنایی', fontSize: 'اندازه قلم', autoTheme: 'پوسته خودکار', displayZoom: 'بزرگ‌نمایی نمایشگر', animations: 'انیمیشن‌ها', reduceMotion: 'کاهش حرکت', autoBrightness: 'روشنایی خودکار', refreshRate: 'نرخ نوسازی', screenTimeout: 'زمان خاموشی صفحه', alwaysOnDisplay: 'نمایشگر همیشه روشن', sounds: 'صداها', haptics: 'لرزش', mediaVolume: 'صدای رسانه', callVolume: 'صدای تماس', notificationVolume: 'صدای اعلان', alarmVolume: 'صدای هشدار', vibration: 'لرزش', ringtone: 'زنگ', notificationSound: 'صدای اعلان', keyboardSound: 'صدای صفحه‌کلید', wifi: 'وای‌فای', mobileData: 'داده همراه', bluetooth: 'بلوتوث', airplaneMode: 'حالت هواپیما', hotspot: 'نقطه اتصال', vpn: 'VPN', permissions: 'مجوزها', highContrast: 'کنتراست بالا', voiceOver: 'VoiceOver', largeText: 'متن بزرگ', boldText: 'متن پررنگ', colorFilters: 'فیلتر رنگ', monoAudio: 'صدای مونو', touchAssistance: 'کمک لمسی', powerSaving: 'صرفه‌جویی انرژی', lowPowerMode: 'حالت کم مصرف', installedApps: 'برنامه‌های نصب‌شده', aboutDevice: 'درباره دستگاه', model: 'مدل', manufacturer: 'سازنده', developerName: 'توسعه‌دهنده', operatingSystem: 'سیستم‌عامل', kernel: 'هسته', buildNumber: 'شماره ساخت', version: 'نسخه', serialNumber: 'شماره سریال', deviceUuid: 'شناسه دستگاه', storageLabel: 'ذخیره‌سازی', ram: 'RAM', cpu: 'پردازنده', gpu: 'گرافیک', batteryHealth: 'سلامت باتری', imei: 'IMEI', small: 'کوچک', medium: 'متوسط', large: 'بزرگ', light: 'روشن', dark: 'تیره', systemTheme: 'سیستم', celsius: 'سلسیوس', fahrenheit: 'فارنهایت', kilometers: 'کیلومتر', miles: 'مایل', format12h: '۱۲ ساعته', format24h: '۲۴ ساعته', seconds: 'ثانیه', minutes: 'دقیقه' },
});
